#!/usr/bin/env perl
use utf8;
binmode STDERR, ':utf8';

use v5.42;
use experimental 'class';

our %SYMBOL_TABLE;  # Global symbol table for variables

our sub DEBUG($msg) { $ENV{DEBUG} && say STDERR "DEBUG: $msg" }
# Base IRNode class
class IRNode {
    use List::Util qw(uniq);

    field @inputs :reader;
    field @control_deps;
    field %attributes;
    field $cached_hash;
    field @dependent_hashes :reader;  # Function pointers to execute after this node
    field $value :reader :writer;           # Cached result value
    field $ready_count :reader = 0; # How many dependencies have completed
    field $total_deps :reader;      # Total number of dependencies needed

    method inc_ready_count() {
        $ready_count++;
        DEBUG ref($self) . "(" . $self->short_id . ") inc_ready_count: now " . $ready_count . "/" . ($total_deps || 0);
    }

    method add_input($node) {
        push @inputs, $node;
        $node->add_dependent($self);
        $total_deps = scalar @inputs;
    }

    method input_at($index) { $inputs[$index] }
    method update_input($index, $node) {
        my $old_node = $inputs[$index];
        my $old_hash = $self->compute_hash();
        DEBUG "Updating input $index from " . ($old_node ? $old_node->to_string : 'undef') . " to " . $node->to_string;
        DEBUG "  Node hash before update: $old_hash";
        $inputs[$index] = $node;
        # Clear cached hash since inputs changed
        $cached_hash = undef;
        my $new_hash = $self->compute_hash();
        DEBUG "  Node hash after update: $new_hash";
        DEBUG "  Hash changed: " . ($old_hash ne $new_hash ? "YES" : "NO");
    }

    method add_dependent($node) {
        DEBUG ref($self) . "(" . $self->short_id . ") adding dependent: " . $node->to_string;
        # we could also use uniq when we notify_dependents which means fewer calls but more memory
        @dependent_hashes = uniq @dependent_hashes, $node->compute_hash;
        DEBUG ref($self) . "(" . $self->short_id . ") now has " . scalar(@dependent_hashes) . " dependents";
    }

    method set_attr($key, $value) { $attributes{$key} = $value }
    method attr($key) { $attributes{$key} }

    # Each subclass implements its own execution logic
    method execute() { ... }
    method operation() { ... }

    method id() { $self->compute_hash }
    method short_id() { substr($self->compute_hash, 0, 8) }

    method compute_hash() {
        return $cached_hash if defined $cached_hash;

        use Digest::SHA qw(sha1_hex);

        my @hash_components = ($self->operation);

        # Add input hashes (sorted for deterministic hashing)
        my @input_hashes = sort map { $_->compute_hash } @inputs;
        push @hash_components, @input_hashes;

        # Add attributes (sorted by key for deterministic hashing)
        for my $key (sort keys %attributes) {
            push @hash_components, "$key=" . ($attributes{$key} // 'undef');
        }

        $cached_hash = sha1_hex(join('|', @hash_components));
        return $cached_hash;
    }

    method to_string() { ref($self) . "(".$self->short_id().")" }

    method DESTROY() {
        DEBUG "DESTROYING " . ref($self) . "(" . substr($self->compute_hash(), 0, 8) . ")";
    }
}

# Specific operation node types
class ConstantNode :isa(IRNode) {
    method operation() { "Constant" }

    method execute() {
        $self->set_value($self->attr('value'));
    }
}

class AddNode :isa(IRNode) {
    method operation() { "Add" }

    method execute() {
        my $left = $self->input_at(0)->value();
        my $right = $self->input_at(1)->value();
        $self->set_value($left + $right);
    }
}

class PrintNode :isa(IRNode) {

    method operation() { "Print" }

    method execute() {
        my $input_val = $self->input_at(0)->value();
        DEBUG "PrintNode executing with value: " . ($input_val // 'undef');
        print $input_val // '';
        $self->set_value($input_val);  # Print passes through its input
    }
}

class StoreNode :isa(IRNode) {
    method operation() { "Store" }

    method execute() {
        my $var_name = $self->attr('var');
        my $stored_value = $self->input_at(0)->value();
        DEBUG "StoreNode($var_name) storing value: '$stored_value'";
        $SYMBOL_TABLE{$var_name} = $stored_value;
        $self->set_value($stored_value);
    }
}

class LoadNode :isa(IRNode) {
    method operation() { "Load" }

    method execute() {
        my $var_name = $self->attr('var');
        my $version = $self->attr('version');
        
        # Check if this is an orphaned LoadNode (version 0 with no inputs)
        if ($version == 0 && !$self->inputs) {
            die qq[Global symbol "\$$var_name" requires explicit package name (did you forget to declare "my \$$var_name"?)];
        }
        
        my $value = $SYMBOL_TABLE{$var_name};
        DEBUG "LoadNode($var_name) executing: symbol_table has " . (defined $value ? "'$value'" : 'undef');
        $self->set_value($value);
    }
}

class ConcatNode :isa(IRNode) {
    method operation() { "Concat" }

    method execute() {
        my $result = "";
        my @inputs = $self->inputs;
        DEBUG "ConcatNode executing with " . scalar(@inputs) . " inputs";
        for my $input (@inputs) {
            my $val = $input->value() // '';
            DEBUG "  Input: " . ref($input) . " value: '$val'";
            $result .= $val;
        }
        DEBUG "ConcatNode result: '$result'";
        $self->set_value($result);
    }
}

class ComparisonNode :isa(IRNode) {
    method operation() { "Comparison" }

    method execute() {
        my $left = $self->input_at(0)->value();
        my $right = $self->input_at(1)->value();
        my $op = $self->attr('op');

        DEBUG "ComparisonNode executing: '$left' $op '$right'";

        my $result;
        if ($op eq 'eq') {
            $result = ($left // '') eq ($right // '') ? 1 : 0;
        } elsif ($op eq 'ne') {
            $result = ($left // '') ne ($right // '') ? 1 : 0;
        } elsif ($op eq '==') {
            $result = $self->to_number($left) == $self->to_number($right) ? 1 : 0;
        } elsif ($op eq '!=') {
            $result = $self->to_number($left) != $self->to_number($right) ? 1 : 0;
        } elsif ($op eq '<') {
            $result = $self->to_number($left) < $self->to_number($right) ? 1 : 0;
        } elsif ($op eq '>') {
            $result = $self->to_number($left) > $self->to_number($right) ? 1 : 0;
        } elsif ($op eq '<=') {
            $result = $self->to_number($left) <= $self->to_number($right) ? 1 : 0;
        } elsif ($op eq '>=') {
            $result = $self->to_number($left) >= $self->to_number($right) ? 1 : 0;
        } else {
            die "Unknown comparison operator: $op";
        }

        DEBUG "ComparisonNode result: $result";
        $self->set_value($result);
    }

    method to_number($val) {
        return 0 + $val;
    }
}

class LogicalAndNode :isa(IRNode) {
    method operation() { "LogicalAnd" }

    method execute() {
        my $left = $self->input_at(0)->value();

        DEBUG "LogicalAndNode executing with left: '$left'";

        # Short-circuit evaluation: if left is false, don't evaluate right
        unless ($self->is_true($left)) {
            DEBUG "LogicalAndNode short-circuit: left is false, returning 0";
            $self->set_value(0);
            return;
        }

        # Left is true, evaluate right
        my $right = $self->input_at(1)->value();
        DEBUG "LogicalAndNode right value: '$right'";

        my $result = $self->is_true($right) ? 1 : 0;
        DEBUG "LogicalAndNode result: $result";
        $self->set_value($result);
    }

    method is_true($val) {
        return !!$val;
    }
}

class LogicalOrNode :isa(IRNode) {
    method operation() { "LogicalOr" }

    method execute() {
        my $left = $self->input_at(0)->value();

        DEBUG "LogicalOrNode executing with left: '$left'";

        # Short-circuit evaluation: if left is true, don't evaluate right
        if ($self->is_true($left)) {
            DEBUG "LogicalOrNode short-circuit: left is true, returning 1";
            $self->set_value(1);
            return;
        }

        # Left is false, evaluate right
        my $right = $self->input_at(1)->value();
        DEBUG "LogicalOrNode right value: '$right'";

        my $result = $self->is_true($right) ? 1 : 0;
        DEBUG "LogicalOrNode result: $result";
        $self->set_value($result);
    }

    method is_true($val) {
        return !!$val;
    }
}

class NotNode :isa(IRNode) {
    method operation() { "Not" }

    method execute() {
        my $input = $self->input_at(0)->value();

        DEBUG "NotNode executing with input: '$input'";

        my $result = $self->is_true($input) ? 0 : 1;
        DEBUG "NotNode result: $result";
        $self->set_value($result);
    }

    method is_true($val) {
        return !!$val;
    }
}

class ThreadedSeaOfNodes {
    field %nodes;           # Hash of nodes by their content hash
    field $entry_node;
    field %symbol_versions; # Track SSA versions: $symbol_versions{var} = current_version

    method create_constant($value) {
        my $node = ConstantNode->new();
        $node->set_attr('value', $value);

        my $hash_key = $node->compute_hash();
        return $nodes{$hash_key} if exists $nodes{$hash_key};

        $nodes{$hash_key} = $node;
        return $node;
    }

    method create_load($var_name) {
        my $version = $symbol_versions{$var_name} // 0;
        DEBUG "create_load($var_name) called, version=$version";

        # Create LoadNode even if variable doesn't exist yet (version == 0)
        # This allows SPPF construction during parsing - orphaned nodes will be cleaned up later
        my $node = LoadNode->new();
        $node->set_attr('var', $var_name);
        $node->set_attr('version', $version);

        if (my $store_node = $self->find_store_node($var_name, $version)) {
            DEBUG "LoadNode($var_name) linking to StoreNode version $version";
            $node->add_input($store_node);
        } else {
            DEBUG "LoadNode($var_name) could not find StoreNode version $version";
        }

        my $hash_key = $node->compute_hash();
        DEBUG "create_load($var_name) computed hash: " . substr($hash_key, 0, 8);
        DEBUG "create_load($var_name) nodes hash has: " . scalar(keys %nodes) . " entries";

        if (exists $nodes{$hash_key}) {
            DEBUG "create_load($var_name) returning existing LoadNode with hash " . substr($hash_key, 0, 8);
            return $nodes{$hash_key};
        }

        $nodes{$hash_key} = $node;
        DEBUG "create_load($var_name) created new LoadNode with hash " . substr($hash_key, 0, 8);
        return $node;
    }

    method find_store_node($var_name, $version) {
        for my $node ($self->nodes) {
            next unless $node->isa('StoreNode');
            next unless $node->attr('var') eq $var_name;
            next unless $node->attr('version') == $version;
            return $node;
        }
        return;
    }
    method create_store($var_name, $value_node) {
        my $version = ($symbol_versions{$var_name} // 0) + 1;
        DEBUG "create_store($var_name) called, version=$version";
        my $node = StoreNode->new();
        $node->add_input($value_node);
        $node->set_attr('var', $var_name);
        $node->set_attr('version', $version);

        my $hash_key = $node->compute_hash();
        if (exists $nodes{$hash_key}) {
            DEBUG "create_store($var_name) returning existing StoreNode with hash " . substr($hash_key, 0, 8);
            return $nodes{$hash_key};
        }

        $symbol_versions{$var_name} = $version;
        $nodes{$hash_key} = $node;
        DEBUG "create_store($var_name) created new StoreNode with hash " . substr($hash_key, 0, 8);
        return $node;
    }

    method create_print($expr_node) {
        my $node = PrintNode->new();
        $node->add_input($expr_node);
        DEBUG "Creating PrintNode with hash: " . $node->compute_hash();

        my $hash_key = $node->compute_hash();
        if (exists $nodes{$hash_key}) {
            DEBUG "Found existing PrintNode with hash: " . $hash_key;
            return $nodes{$hash_key} ;
        }

        $nodes{$hash_key} = $node;
        return $node;
    }

    method create_add($left_node, $right_node) {
        my $node = AddNode->new();
        $node->add_input($left_node);
        $node->add_input($right_node);

        my $hash_key = $node->compute_hash();
        return $nodes{$hash_key} if exists $nodes{$hash_key};

        $nodes{$hash_key} = $node;
        return $node;
    }

    method create_concat(@expr_nodes) {
        my $node = ConcatNode->new();
        $node->add_input($_) for @expr_nodes;

        my $hash_key = $node->compute_hash();
        DEBUG "create_concat: hash_key = $hash_key";
        if (exists $nodes{$hash_key}) {
            DEBUG "create_concat: returning existing node";
            return $nodes{$hash_key};
        }

        $nodes{$hash_key} = $node;
        DEBUG "create_concat: stored new ConcatNode in nodes hash";
        return $node;
    }

    method create_comparison($op, $left_node, $right_node) {
        my $node = ComparisonNode->new();
        DEBUG "create_comparison: adding left input: " . $left_node->to_string;
        $node->add_input($left_node);
        DEBUG "create_comparison: adding right input: " . $right_node->to_string;
        $node->add_input($right_node);
        $node->set_attr('op', $op);

        my $hash_key = $node->compute_hash();
        DEBUG "create_comparison: computed hash: " . substr($hash_key, 0, 8);

        if (exists $nodes{$hash_key}) {
            DEBUG "create_comparison: returning existing ComparisonNode";
            return $nodes{$hash_key};
        }

        $nodes{$hash_key} = $node;
        DEBUG "create_comparison: created new ComparisonNode with " . scalar($node->inputs) . " inputs";
        return $node;
    }

    method create_logical_and($left_node, $right_node) {
        my $node = LogicalAndNode->new();
        $node->add_input($left_node);
        $node->add_input($right_node);

        my $hash_key = $node->compute_hash();
        return $nodes{$hash_key} if exists $nodes{$hash_key};

        $nodes{$hash_key} = $node;
        return $node;
    }

    method create_logical_or($left_node, $right_node) {
        my $node = LogicalOrNode->new();
        $node->add_input($left_node);
        $node->add_input($right_node);

        my $hash_key = $node->compute_hash();
        return $nodes{$hash_key} if exists $nodes{$hash_key};

        $nodes{$hash_key} = $node;
        return $node;
    }

    method create_not($input_node) {
        my $node = NotNode->new();
        $node->add_input($input_node);

        my $hash_key = $node->compute_hash();
        return $nodes{$hash_key} if exists $nodes{$hash_key};

        $nodes{$hash_key} = $node;
        return $node;
    }

    method nodes() { values %nodes }
    method node_count() { scalar keys %nodes }

    method try_execute_node($node_hash) {
      DEBUG "try_execute_node called with hash: $node_hash";
      my $node = $nodes{$node_hash};
      unless ($node) {
          DEBUG "  Node not found in nodes hash!";
          DEBUG "  Available hashes: " . join(", ", map { substr($_, 0, 8) } sort keys %nodes);
          return;
      }

      my @inputs = $node->inputs;
      DEBUG "  Found node: " . ref($node) . " with " . scalar(@inputs) . " inputs";

      # Check if all inputs have computed values (are ready)
      for my $i (0 .. $#inputs) {
          my $input = $inputs[$i];
          unless (defined $input->value) {
              DEBUG "  Input $i (" . ref($input) . ") not ready yet";
              return;
          }
          DEBUG "  Input $i (" . ref($input) . ") has value: '" . ($input->value // 'undef') . "'";
      }

      DEBUG "  All inputs ready - executing node!";
      $node->execute();
      $self->notify_dependents($node_hash);
   }

   method notify_dependents($node_hash) {
       my $node = $nodes{$node_hash} or return;
       DEBUG "notify_dependents called for " . ref($node) . "(" . $node->short_id . ")";
       DEBUG "  has " . scalar($node->dependent_hashes) . " dependent entries";

       # Notify each dependent once per dependency relationship
       # This allows nodes with same input multiple times to get multiple notifications
       for my $dependent_hash ($node->dependent_hashes) {
           DEBUG "  notifying dependent: $dependent_hash";
           $self->try_execute_node($dependent_hash);
       }
   }

   method execute_threaded() {
       # Run peephole optimizations first
       $self->run_peephole_optimizations();

       # Clean up unreferenced nodes
       $self->cleanup_orphaned_nodes();

       my @leaf_nodes = grep { scalar($_->inputs) == 0 } $self->nodes;
       DEBUG "Found " . scalar(@leaf_nodes) . " leaf nodes";

       for my $leaf (@leaf_nodes) {
           my $type = ref($leaf);
           my $extra = "";
           if ($leaf->isa('StoreNode') || $leaf->isa('LoadNode')) {
               $extra = " var=" . ($leaf->attr('var') // 'unknown');
           }
           DEBUG "Trying to execute leaf node: $type$extra (" . $leaf->compute_hash(). ")";
           $self->try_execute_node($leaf->compute_hash());
       }
   }

   method dump_graph() {
       say "Generated Sea of Nodes with " . $self->node_count . " nodes";

       # Debug: show the generated nodes
       my @nodes = $self->nodes;
       for my $node (@nodes) {
           my $class_name = ref($node);
           $class_name =~ s/.*:://;  # Remove package prefix
           say $node->to_string;

           if ($node->operation eq 'Constant') {
               say "  Value: '" . ($node->attr('value') // 'undef') . "'";
           } elsif ($node->operation eq 'Store' || $node->operation eq 'Load') {
               say "  Variable: " . ($node->attr('var') // 'undef') .
                   " v" . ($node->attr('version') // 'undef');
           }

           if ($node->inputs) {
               say "  Inputs: " . join(', ', map { $_->to_string } $node->inputs);
           }
       }

       say "\n=== Dependency Graph ===";
       for my $node (@nodes) {
           my $short_id = $node->short_id;
           my @inputs = $node->inputs;
           if (@inputs) {
               for my $input (@inputs) {
                   say $input->short_id . " -> " . $short_id;
               }
           } else {
               say $short_id . " (leaf node)";
           }
       }
   }

   method run_peephole_optimizations() {
       DEBUG "Running peephole optimizations";

       # Find all ConstantNodes marked for interpolation
       for my $node ($self->nodes) {
           next unless $node->isa('ConstantNode');
           next unless $node->attr('needs_interpolation');

           my $content = $node->attr('value');
           DEBUG "Checking for interpolation in: $content";

           # Look for $identifier patterns
           if ($content =~ /\$(\w+)/) {
               DEBUG "Found variable interpolation: \$$1";
               $self->replace_with_interpolation($node, $content);
           }
       }
   }

   method replace_with_interpolation($const_node, $content) {
       my @parts;
       my $pos = 0;

       # Parse the string looking for $identifier patterns
       while ($content =~ /\G(.*?)\$(\w+)/gc) {
           my ($prefix, $var_name) = ($1, $2);

           # Add literal text before the variable
           if (length($prefix) > 0) {
               push @parts, $self->create_constant($prefix);
           }

           # Add variable load
           push @parts, $self->create_load($var_name);
           DEBUG "Added interpolation for variable: $var_name";
       }

       # Add any remaining literal text
       if ($content =~ /\G(.+)$/gc) {
           push @parts, $self->create_constant($1);
       }

       # If we have multiple parts, create a concat node
       if (@parts > 1) {
           my $concat_node = $self->create_concat(@parts);

           # Update all references to the old constant node
           $self->replace_node_references($const_node, $concat_node);
       }
   }

   method replace_node_references($old_node, $new_node) {
       my $old_hash = $old_node->compute_hash();
       my $new_hash = $new_node->compute_hash();

       DEBUG "Replacing references from $old_hash to $new_hash (simpler approach)";

       # For now, let's just fix the immediate problem by updating %nodes
       # when a node's hash changes after update_input

       # Find all nodes that reference the old node and update them
       for my $node ($self->nodes) {
           my @inputs = $node->inputs;
           for (my $i = 0; $i < @inputs; $i++) {
               if ($inputs[$i] == $old_node) {
                   DEBUG "  Updating input $i of " . ref($node);

                   # Get the old hash before update
                   my $node_old_hash = $node->compute_hash();

                   # Update the input (this changes the node's hash)
                   $node->update_input($i, $new_node);

                   # Get the new hash after update
                   my $node_new_hash = $node->compute_hash();

                   # Update %nodes to reflect the hash change
                   if ($node_old_hash ne $node_new_hash) {
                       DEBUG "    Updating %nodes: $node_old_hash -> $node_new_hash";
                       # commented out deleting nodes during replacement for now
                       # delete $nodes{$node_old_hash};
                       $nodes{$node_new_hash} = $node;
                   }

                   # Update dependency tracking
                   $new_node->add_dependent($node);
               }
           }
       }

       DEBUG "Node reference replacement complete";
   }

   method create_node_with_inputs($original_node, @new_inputs) {
       # Create a new node of the same type but with different inputs
       my $class = ref($original_node);

       if ($class eq 'PrintNode') {
           return $self->create_print($new_inputs[0]);
       } elsif ($class eq 'AddNode') {
           return $self->create_add($new_inputs[0], $new_inputs[1]);
       } elsif ($class eq 'ConcatNode') {
           return $self->create_concat(@new_inputs);
       } elsif ($class eq 'StoreNode') {
           my $var = $original_node->attr('var');
           return $self->create_store($var, $new_inputs[0]);
       } elsif ($class eq 'ComparisonNode') {
           my $op = $original_node->attr('op');
           return $self->create_comparison($op, $new_inputs[0], $new_inputs[1]);
       } elsif ($class eq 'LogicalAndNode') {
           return $self->create_logical_and($new_inputs[0], $new_inputs[1]);
       } elsif ($class eq 'LogicalOrNode') {
           return $self->create_logical_or($new_inputs[0], $new_inputs[1]);
       } elsif ($class eq 'NotNode') {
           return $self->create_not($new_inputs[0]);
       } elsif ($class eq 'LoadNode' || $class eq 'ConstantNode') {
           # These don't have inputs, so no replacement needed
           return undef;
       }

       DEBUG "Warning: Unknown node type for replacement: $class";
       return undef;
   }

   method cleanup_orphaned_nodes() {
       DEBUG "Cleaning up orphaned nodes";
       my $before_count = scalar keys %nodes;

       # Find all nodes that are reachable from leaf nodes
       my %reachable;

       # Start with leaf nodes that have dependents (are actually used)
       my @to_visit;
       for my $node ($self->nodes) {
           if (scalar($node->inputs) == 0 && $node->dependent_hashes) {
               push @to_visit, $node->compute_hash;
               $reachable{$node->compute_hash} = 1;
           }
       }

       # Trace through all dependencies
       while (@to_visit) {
           my $hash = shift @to_visit;
           my $node = $nodes{$hash} or next;

           # Mark all nodes that this node depends on
           for my $dep_hash ($node->dependent_hashes) {
               unless ($reachable{$dep_hash}) {
                   $reachable{$dep_hash} = 1;
                   push @to_visit, $dep_hash;
               }
           }
       }

       # Remove unreachable nodes
       my @to_remove;
       for my $hash (keys %nodes) {
           unless ($reachable{$hash}) {
               push @to_remove, $hash;
           }
       }

       for my $hash (@to_remove) {
           DEBUG "Removing orphaned node: $hash (" . ref($nodes{$hash}) . ")";
           delete $nodes{$hash};
       }

       my $after_count = scalar keys %nodes;
       DEBUG "Cleaned up " . (@to_remove) . " orphaned nodes ($before_count -> $after_count)";
   }
}

# Grammar rule with semantic action
class GrammarRule {
    use experimental 'keyword_any';

    field $lhs :param :reader;          # Left-hand side nonterminal
    field $rhs :param :reader;          # Right-hand side symbols
    field $semantic_action :param;  # Code reference for building IR
    field $cached_id;

    method matches($symbols) {
        for my $s (@$symbols) {
            return 0 unless any { $s eq $_ } @$rhs;
        }
        return 1;
    }

    method rhs_length() { scalar @$rhs }
    method rhs_at($pos) { $rhs->[$pos] }

    method id() {
        return $cached_id if defined $cached_id;

        use Digest::SHA qw(sha1_hex);
        use Scalar::Util qw(refaddr);

        my @hash_components = ($lhs);
        push @hash_components, @$rhs;
        # Include semantic action address so rules with same grammar
        # but different actions are considered different
        push @hash_components, refaddr($semantic_action);

        $cached_id = sha1_hex(join('|', @hash_components));
        return $cached_id;
    }

    method execute_action($matches, $ir_graph) {
        return $semantic_action->($matches, $ir_graph);
    }

    method to_string() {
        return $lhs . " → " . join(' ', @$rhs);
    }
}

# Earley item
class EarleyItem {
    use Digest::SHA qw(sha1_hex);
    
    field $rule :param :reader;
    field $dot_pos :param :reader = 0;
    field $start_pos :param :reader = 0;
    field $current_pos :param :reader :writer = 0;
    field $matched_text :param :reader :writer = "";
    field $semantic_value :param :reader = undef;
    field $hash = undef;

    method set_semantic_value($value) {
        $semantic_value = $value;
    }
    
    method compute_hash() {
        return $hash if defined $hash;
        
        # Hash based on rule ID, dot position, and start position
        # These three values uniquely identify an Earley item's parse state
        my $content = join(':', 
            $rule->id,
            $dot_pos,
            $start_pos
        );
        
        $hash = sha1_hex($content);
        return $hash;
    }

    method is_complete() { $dot_pos >= $rule->rhs_length }
    method next_symbol() {
        return undef if $self->is_complete;
        return $rule->rhs_at($dot_pos);
    }

    method advance($matched_char = "") {
        DEBUG "Advancing item: " . $self->to_string;
        EarleyItem->new(
            rule => $rule,
            dot_pos => $dot_pos + 1,
            start_pos => $start_pos,
            current_pos => $current_pos,
            matched_text => $matched_text . $matched_char,
        );
    }

    method to_string() {
      my @rhs = $rule->rhs->@*;
      my @parts;
      for my $i (0 .. @rhs) {
          if ($i == $dot_pos) {
              push @parts, "•";
          }
          if ($i < @rhs) {
              push @parts, $rhs[$i];
          }
      }
      return $rule->lhs . " → " . join(' ', @parts);
    }
}

class ScanlessEarleyParser {
    field @grammar_rules;
    field $ir_graph = ThreadedSeaOfNodes->new();
    field @chart;  # Array of state sets
    field $input_text;
    field %nonterminals;

    ADJUST {
        $self->define_grammar();
    }

    method define_grammar() {
        @grammar_rules = (
            # Program → StatementSeq
            GrammarRule->new(
                lhs => 'Program',
                rhs => ['StatementSeq'],
                semantic_action => sub ($matches, $ir) {
                    return $matches->[0];
                }
            ),


            # StatementSeq → Statement
            GrammarRule->new(
                lhs => 'StatementSeq',
                rhs => ['Statement'],
                semantic_action => sub ($matches, $ir) {
                    return $matches->[0];
                }
            ),

            # StatementSeq → Statement ';' WS StatementSeq
            GrammarRule->new(
                lhs => 'StatementSeq',
                rhs => ['Statement', ';', 'WS', 'StatementSeq'],
                semantic_action => sub ($matches, $ir) {
                    # Sequential composition - return the last statement
                    return $matches->[3];
                }
            ),

            # Statement → Expression
            GrammarRule->new(
                lhs => 'Statement',
                rhs => ['Expression'],
                semantic_action => sub ($matches, $ir) {
                    return $matches->[0];
                }
            ),

            # Expression → StringLiteral
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['StringLiteral'],
                semantic_action => sub ($matches, $ir) {
                    return $matches->[0];
                }
            ),
            
            # Expression → PrintExpr
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['PrintExpr'],
                semantic_action => sub ($matches, $ir) {
                    return $matches->[0];
                }
            ),

            # Expression → Variable
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['Variable'],
                semantic_action => sub ($matches, $ir) {
                    my $var_name = $matches->[0]{var_name};
                    my $load_node = $ir->create_load($var_name);
                    return $load_node;
                }
            ),

            # Expression → Assignment (assignments are expressions)
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['Assignment'],
                semantic_action => sub ($matches, $ir) {
                    return $matches->[0];
                }
            ),


            # Expression → StringLiteral ComparisonOp StringLiteral
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['StringLiteral', 'WS', 'ComparisonOp', 'WS', 'StringLiteral'],
                semantic_action => sub ($matches, $ir) {
                    my $op = $matches->[2]{op};
                    return $ir->create_comparison($op, $matches->[0], $matches->[4]);
                }
            ),

            # Expression → Variable ComparisonOp StringLiteral
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['Variable', 'WS', 'ComparisonOp', 'WS', 'StringLiteral'],
                semantic_action => sub ($matches, $ir) {
                    my $var_name = $matches->[0]{var_name};
                    my $left_node = $ir->create_load($var_name);
                    my $op = $matches->[2]{op};
                    return $ir->create_comparison($op, $left_node, $matches->[4]);
                }
            ),

            # Expression → StringLiteral ComparisonOp Variable
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['StringLiteral', 'WS', 'ComparisonOp', 'WS', 'Variable'],
                semantic_action => sub ($matches, $ir) {
                    my $var_name = $matches->[4]{var_name};
                    my $right_node = $ir->create_load($var_name);
                    my $op = $matches->[2]{op};
                    return $ir->create_comparison($op, $matches->[0], $right_node);
                }
            ),

            # Expression → Variable ComparisonOp Variable
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['Variable', 'WS', 'ComparisonOp', 'WS', 'Variable'],
                semantic_action => sub ($matches, $ir) {
                    my $left_var = $matches->[0]{var_name};
                    my $right_var = $matches->[4]{var_name};
                    my $left_node = $ir->create_load($left_var);
                    my $right_node = $ir->create_load($right_var);
                    my $op = $matches->[2]{op};
                    return $ir->create_comparison($op, $left_node, $right_node);
                }
            ),

            # ComparisonOp → 'eq'
            GrammarRule->new(
                lhs => 'ComparisonOp',
                rhs => ['eq'],
                semantic_action => sub ($matches, $ir) {
                    return { op => 'eq' };
                }
            ),

            # ComparisonOp → 'ne'
            GrammarRule->new(
                lhs => 'ComparisonOp',
                rhs => ['ne'],
                semantic_action => sub ($matches, $ir) {
                    return { op => 'ne' };
                }
            ),

            # ComparisonOp → '=='
            GrammarRule->new(
                lhs => 'ComparisonOp',
                rhs => ['=='],
                semantic_action => sub ($matches, $ir) {
                    return { op => '==' };
                }
            ),

            # ComparisonOp → '!='
            GrammarRule->new(
                lhs => 'ComparisonOp',
                rhs => ['!='],
                semantic_action => sub ($matches, $ir) {
                    return { op => '!=' };
                }
            ),

            # Expression → Expression '&&' Expression
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['Expression', 'WS', '&&', 'WS', 'Expression'],
                semantic_action => sub ($matches, $ir) {
                    return $ir->create_logical_and($matches->[0], $matches->[4]);
                }
            ),

            # Expression → Expression '||' Expression
            GrammarRule->new(
                lhs => 'Expression',
                rhs => ['Expression', 'WS', '||', 'WS', 'Expression'],
                semantic_action => sub ($matches, $ir) {
                    return $ir->create_logical_or($matches->[0], $matches->[4]);
                }
            ),

            # PrintExpr → 'print' WS Expression
            GrammarRule->new(
                lhs => 'PrintExpr',
                rhs => ['print', 'WS', 'Expression'],
                semantic_action => sub ($matches, $ir) {
                    my $expr_node = $matches->[2];
                    my $print_node = $ir->create_print($expr_node);
                    return $print_node;
                }
            ),

            # Assignment → Variable WS '=' WS Expression
            GrammarRule->new(
                lhs => 'Assignment',
                rhs => ['Variable', 'WS', '=', 'WS', 'Expression'],
                semantic_action => sub ($matches, $ir) {
                    my $var_name = $matches->[0]{var_name};
                    my $expr_node = $matches->[4];
                    my $store_node = $ir->create_store($var_name, $expr_node);
                    return $store_node;
                }
            ),

            # StringLiteral → '"' InterpolatedContent '"' (interpolated)
            GrammarRule->new(
                lhs => 'StringLiteral',
                rhs => ['"', 'InterpolatedContent', '"'],
                semantic_action => sub ($matches, $ir) {
                    my $node = $matches->[1];

                    # Process escape sequences for double-quoted strings
                    my $content = $node->attr('value');
                    $content =~ s/\\n/\n/g;   # newline
                    $content =~ s/\\t/\t/g;   # tab
                    $content =~ s/\\r/\r/g;   # carriage return
                    $content =~ s/\\\\/\\/g;  # backslash
                    $content =~ s/\\"/"/g;    # double quote
                    # Note: \$ should stay as \$ for now - the interpolation handler will deal with literal $
                    $node->set_attr('value', $content);

                    # Mark the final node for interpolation
                    $node->set_attr('needs_interpolation', 1);
                    DEBUG "StringLiteral: processed escapes and marking final string '" . $node->attr('value') . "' for interpolation";
                    return $node;
                }
            ),

            # StringLiteral → "'" StringContent "'"
            GrammarRule->new(
                lhs => 'StringLiteral',
                rhs => ["'", 'StringContent', "'"],
                semantic_action => sub ($matches, $ir) {
                    my $content = $matches->[1]{text};
                    my $const_node = $ir->create_constant($content);
                    return $const_node;
                }
            ),

            # StringContent → CharSeq (for single-quoted strings)
            GrammarRule->new(
                lhs => 'StringContent',
                rhs => ['CharSeq'],
                semantic_action => sub ($matches, $ir) {
                    DEBUG "StringContent CharSeq: " . $matches->[0]{text};
                    return { text => $matches->[0]{text} };
                }
            ),

            # InterpolatedContent → CharSeq (same as StringContent but will be marked for interpolation)
            GrammarRule->new(
                lhs => 'InterpolatedContent',
                rhs => ['CharSeq'],
                semantic_action => sub ($matches, $ir) {
                    my $content = $matches->[0]{text};
                    DEBUG "InterpolatedContent semantic action called with: '$content'";
                    my $const_node = $ir->create_constant($content);
                    # Don't mark for interpolation yet - let StringLiteral decide
                    # when it has the complete string
                    return $const_node;
                }
            ),

            # CharSeq → Char CharSeq
            GrammarRule->new(
                lhs => 'CharSeq',
                rhs => ['Char', 'CharSeq'],
                semantic_action => sub ($matches, $ir) {
                    DEBUG "CharSeq (recursive) semantic action: building '" . $matches->[0]{char} . "' + '" . ($matches->[1]{text} // '') . "'";
                    return { text => $matches->[0]{char} . $matches->[1]{text} // '' };
                }
            ),

            # CharSeq → Char
            GrammarRule->new(
                lhs => 'CharSeq',
                rhs => ['Char'],
                semantic_action => sub ($matches, $ir) {
                    return { text => $matches->[0]{char} };
                }
            ),

            # Variable → '$' Identifier
            GrammarRule->new(
                lhs => 'Variable',
                rhs => ['$', 'Identifier'],
                semantic_action => sub ($matches, $ir) {
                    return { var_name => $matches->[1]{name} };
                }
            ),

            # Identifier → Letter LetterDigitSeq
            GrammarRule->new(
                lhs => 'Identifier',
                rhs => ['Letter', 'LetterDigitSeq'],
                semantic_action => sub ($matches, $ir) {
                    return { name => $matches->[0]{char} . $matches->[1]{text} };
                }
            ),

            # Identifier → Letter
            GrammarRule->new(
                lhs => 'Identifier',
                rhs => ['Letter'],
                semantic_action => sub ($matches, $ir) {
                    return { name => $matches->[0]{char} };
                }
            ),

            # LetterDigitSeq → LetterDigit LetterDigitSeq
            GrammarRule->new(
                lhs => 'LetterDigitSeq',
                rhs => ['LetterDigit', 'LetterDigitSeq'],
                semantic_action => sub ($matches, $ir) {
                    return { text => $matches->[0]{char} . $matches->[1]{text} };
                }
            ),

            # LetterDigitSeq → LetterDigit
            GrammarRule->new(
                lhs => 'LetterDigitSeq',
                rhs => ['LetterDigit'],
                semantic_action => sub ($matches, $ir) {
                    return { text => $matches->[0]{char} };
                }
            ),

            # WS → Whitespace WS
            GrammarRule->new(
                lhs => 'WS',
                rhs => ['Whitespace', 'WS'],
                semantic_action => sub ($matches, $ir) {
                    return undef;  # Whitespace has no semantic value
                }
            ),

            # WS → Whitespace
            GrammarRule->new(
                lhs => 'WS',
                rhs => ['Whitespace'],
                semantic_action => sub ($matches, $ir) {
                    return undef;
                }
            ),

            # WS → ε (empty)
            GrammarRule->new(
                lhs => 'WS',
                rhs => [],
                semantic_action => sub ($matches, $ir) {
                    return undef;
                }
            ),

            # Handle comments as statements
            GrammarRule->new(
                lhs => 'Statement',
                rhs => ['Comment'],
                semantic_action => sub ($matches, $ir) {
                    return undef;  # Comments produce no semantic value
                }
            ),

            # Comment → '#' CommentText '\n'
            GrammarRule->new(
                lhs => 'Comment',
                rhs => ['#', 'CommentText', '\n'],
                semantic_action => sub ($matches, $ir) {
                    return undef;
                }
            ),

            # CommentText → CommentLineChar CommentText | ε
            GrammarRule->new(
                lhs => 'CommentText',
                rhs => ['CommentLineChar', 'CommentText'],
                semantic_action => sub ($matches, $ir) {
                    return undef;
                }
            ),

            GrammarRule->new(
                lhs => 'CommentText',
                rhs => [],
                semantic_action => sub ($matches, $ir) {
                    return undef;
                }
            ),

        );

        %nonterminals = map { $_->lhs => $_ } @grammar_rules;
    }


    method parse($text) {
        $input_text = $text;
        @chart = ();
        my %seen_items;  # Track items by hash to prevent duplicates

        DEBUG "Parsing text: $text";
        # Initialize chart with start state - predict all Program rules
        $chart[0] = [
            map { EarleyItem->new( rule => $_ ) }
            grep { $_->lhs eq 'Program' } @grammar_rules
        ];
        
        # Mark initial items as seen
        for my $item (@{$chart[0]}) {
            $seen_items{$item->compute_hash()} = 1;
        }
        
        # Helper to add item only if not seen
        my $add_item = sub ($item, $chart_pos, $to_agenda) {
            my $item_hash = $item->compute_hash();
            if (!$seen_items{$item_hash}) {
                $seen_items{$item_hash} = 1;
                push @{$chart[$chart_pos]}, $item;
                push @$to_agenda, $item if $to_agenda;
                DEBUG "Added new item: " . $item->to_string;
                return 1;
            }
            DEBUG "Skipping duplicate item: " . $item->to_string;
            return 0;
        };

        # Main parsing loop - process each character position
        for my $pos (0 .. length($text)) {
            DEBUG "Processing position $pos";
            $chart[$pos] //= [];

            my $agenda = [@{$chart[$pos]}];
            DEBUG "Agenda: " . join(', ', map { $_->to_string } @$agenda);
            while (@$agenda) {
                my $item = shift @$agenda;

                if ($item->is_complete) {
                    DEBUG "Completed item: " . $item->to_string;
                    $self->complete($item, $pos, $agenda);
                } else {
                    my $next_sym = $item->next_symbol;
                    if ($self->is_character_class($next_sym)) {
                        $self->scan_character($item, $pos, $text);
                    } elsif ($self->is_nonterminal($next_sym)) {
                       $self->predict($item, $pos, $agenda);
                    } else {
                        $self->scan_literal($item, $pos, $text);
                    }
                }
            }
        }
        return $ir_graph;
    }

    method is_nonterminal($symbol) {
        return exists $nonterminals{$symbol};
    }


    method find_actual_completion($symbol, $start_pos, $parent_item, $parent_end_pos) {
        DEBUG "Finding actual completion for $symbol starting at $start_pos";

      # Handle end-of-input case: if we're past the input length, check for empty rules
      if ($start_pos >= length($input_text)) {
          # Look for empty rules for this symbol in the grammar
          for my $rule (@grammar_rules) {
              if ($rule->lhs eq $symbol && @{$rule->rhs} == 0) {
                  DEBUG "Found empty rule for $symbol at end of input: " . $rule->lhs . " → ε";
                  # Execute semantic action for empty rule
                  my $semantic_value = $rule->execute_action([], $ir_graph);
                  return {
                      semantic_value => $semantic_value,
                      end_pos => $start_pos
                  };
              }
          }
          DEBUG "No empty rule found for $symbol at end of input";
      }

      # Strategy 1: Look for completed items across all chart positions
      my @all_candidates = map {
          $chart[$_] ? grep {
              DEBUG "Checking item: " . $_->to_string . " complete=" . $_->is_complete .
                    " lhs_match=" . ($_->rule->lhs eq $symbol) .
                    " start_pos=" . $_->start_pos . " looking_for=" . $start_pos .
                    " consumed=" . ($_->current_pos > $_->start_pos) .
                    " child_ok=" . $self->could_be_child_of($_, $parent_item);
              $_->is_complete &&
              $_->rule->lhs eq $symbol &&
              $_->start_pos == $start_pos &&
              $self->could_be_child_of($_, $parent_item)
          } @{$chart[$_]} : ()
      } ($start_pos .. $parent_end_pos);

      DEBUG "All candidates for $symbol at $start_pos:";
      for my $cand (@all_candidates) {
          DEBUG "  " . $cand->to_string . " span=" . ($cand->current_pos - $cand->start_pos);
      }
      my ($best_item) = sort {
          # we want the item with the longest span
          ($b->current_pos - $b->start_pos) <=> ($a->current_pos - $a->start_pos)
      } @all_candidates;

      if ($best_item) {
          DEBUG "Found best item: " . $best_item->to_string;
          return {
              semantic_value => $best_item->semantic_value,
              end_pos => $best_item->current_pos
          };
      }

      DEBUG "No perfect completion found for symbol '$symbol' at position $start_pos";
      DEBUG "Available candidates were:";
      for my $pos ($start_pos .. $parent_end_pos) {
          next unless $chart[$pos];
          for my $item (@{$chart[$pos]}) {
              if ($item->rule->lhs eq $symbol && $item->start_pos == $start_pos) {
                  DEBUG "  " . $item->to_string . " (complete=" . $item->is_complete . ", consumed=" . ($item->current_pos - $item->start_pos) . ")";
              }
          }
      }
      die "Parse failed: Could not find complete parse for '$symbol' starting at position $start_pos";
    }

    method reconstruct_from_partials($symbol, $start_pos, $parent_end_pos) {
      # Strategy 2: When we can't find a perfect completion,
      # try to reconstruct from available partial information

      # Look for any item that started at the right position for this symbol
      for my $chart_pos ($start_pos .. $parent_end_pos) {
          next unless $chart[$chart_pos];

          for my $item (@{$chart[$chart_pos]}) {
              if ($item->rule->lhs eq $symbol &&
                  $item->start_pos == $start_pos) {

                  # Found an item for this symbol, even if not complete
                  # Return what we can determine
                  return {
                      semantic_value => $item->semantic_value,
                      end_pos => $item->current_pos || $chart_pos
                  };
              }
          }
      }

      # If we still can't find anything, return a placeholder
      return {
          semantic_value => undef,
          end_pos => $start_pos  # No progress made
      };
   }

    method could_be_child_of($child_item, $parent_item) {
      # Check if this child could logically be part of the parent's parse
      return $child_item->current_pos <= $parent_item->current_pos &&
             $child_item->start_pos >= $parent_item->start_pos;
    }

    method find_completed_item($symbol, $start_pos) {
        DEBUG "Finding completed item for $symbol starting at $start_pos";
      # Search through all chart positions from start_pos forward
      for my $chart_pos ($start_pos .. $#chart) {
          DEBUG "Checking chart position $chart_pos";
          next unless $chart[$chart_pos];
          DEBUG "Chart position $chart_pos has items";
          for my $item (@{$chart[$chart_pos]}) {
              DEBUG "Checking item " . $item->to_string;
              if ($item->is_complete &&
                  $item->rule->lhs eq $symbol &&
                  $item->start_pos == $start_pos) {
                  DEBUG "Found completed item: " . $item->to_string;
                  return $item;
              }
          }
      }
      return;
    }

    method collect_child_values($item, $end_pos) {
        my $rule = $item->rule;
        my @rhs = $rule->rhs->@*;
        my @values;

        my @parse_path = $self->reconstruct_parse_path($item, $end_pos);

        for my $i (0..$#rhs) {
            my $s = $rhs[$i];
            if ($self->is_character_class($s)) {
                my $char = substr($input_text, $parse_path[$i]->{pos}, 1);
                push @values, { char => $char };
            }
            elsif ($self->is_nonterminal($s)) {
                    push @values, $parse_path[$i]->{semantic_value};
            } else { # literal no semantic value, just advance position
                push @values, undef;
            }
        }
        return @values;
    }

    method reconstruct_parse_path($completed_item, $end_pos) {
      DEBUG "Reconstructing parse path for " . $completed_item->to_string;
      my $rule = $completed_item->rule;
      my @rhs = $rule->rhs->@*;
      my @path;

      # Start from the beginning of this item
      my $current_pos = $completed_item->start_pos;

      for my $i (0 .. $#rhs) {
          my $symbol = $rhs[$i];
          DEBUG "Processing symbol $symbol";
          if ($self->is_character_class($symbol)) {
              DEBUG "Character class: $symbol";
              # Character: record position and advance
              push @path, {
                  symbol => $symbol,
                  pos => $current_pos,
                  type => 'character'
              };
              $current_pos += 1;
          }
          elsif ($self->is_nonterminal($symbol)) {
              DEBUG "Nonterminal: $symbol";
              DEBUG "Looking for $symbol completion starting at $current_pos (after processing previous symbols)";
              # Nonterminal: find what actually completed here
              my $child_completion = $self->find_actual_completion(
                  $symbol, $current_pos, $completed_item, $end_pos
              );

              if ($child_completion) {
                  push @path, {
                      symbol => $symbol,
                      pos => $current_pos,
                      type => 'nonterminal',
                      semantic_value => $child_completion->{semantic_value},
                      end_pos => $child_completion->{end_pos}
                  };
                  $current_pos = $child_completion->{end_pos};
              }
          }
          else {
              DEBUG "Literal: $symbol";
              # Literal: record position and advance
              push @path, {
                  symbol => $symbol,
                  pos => $current_pos,
                  type => 'literal'
              };
              $current_pos += length($symbol);
          }
      }

      return @path;
    }

    method complete($item, $pos, $agenda) {
        DEBUG "Completing item " . $item->to_string;
        my $rule = $item->rule; # Get the rule that just completed
        my @child_values = $self->collect_child_values($item, $pos);

        # Execute semantic action when rule completes
        my $semantic_value = undef;
        try {
            DEBUG "Executing semantic action for rule: " . $rule->to_string . " (id: " . $rule->id . ")";
            $semantic_value = $rule->execute_action(\@child_values, $ir_graph);
        }
        catch($e) {
            warn "Error executing semantic action for rule " . $rule->id . ": $e";
        }

        $item->set_semantic_value($semantic_value);

        # Standard Earley completion
        for my $waiting_item (@{$chart[$item->start_pos]}) {
            DEBUG "Checking waiting item " . $waiting_item->to_string;
            next if $waiting_item->is_complete;
            DEBUG "\tWaiting item is not complete";
            next unless defined $waiting_item->next_symbol;
            DEBUG "\tWaiting item has next symbol";
            next unless $waiting_item->next_symbol eq $rule->lhs;
            DEBUG "\tComparing '" . ($waiting_item->next_symbol // 'undef') . "' eq '" . ($rule->lhs //
  'undef') . "'";
            DEBUG "\tWaiting item has correct next symbol";

            my $new_item = $waiting_item->advance;
            DEBUG "Set current_pos to $pos for item: " . $new_item->to_string;
            $new_item->set_current_pos($pos);
            DEBUG "\tNew item: " . $new_item->to_string;
            
            # Check if this item already exists before adding
            my $already_exists = 0;
            for my $existing_item (@{$chart[$pos]}) {
                if ($existing_item->rule == $new_item->rule && 
                    $existing_item->start_pos == $new_item->start_pos && 
                    $existing_item->dot_pos == $new_item->dot_pos) {
                    DEBUG "Item already exists in chart, skipping";
                    $already_exists = 1;
                    last;
                }
            }
            
            if (!$already_exists) {
                push @$agenda, $new_item;
                push @{$chart[$pos]}, $new_item;
            }
        }
        DEBUG "Item completed with semantic value: " . (defined $semantic_value ? $semantic_value :
  'undef');
    }

    method scan_character($item, $pos, $text) {
        return if $pos >= length($text);

        my $char = substr($text, $pos, 1);
        my $expected = $item->next_symbol;

        if ($self->matches_character_class($char, $expected)) {
            my $new_item = $item->advance($char);
            $new_item->set_current_pos( $pos + 1 );

            # Store the matched character for semantic actions
            if ($expected eq 'Char') {
                $new_item->set_semantic_value({ char => $char });
            }

            push @{$chart[$pos + 1]}, $new_item;
        }
    }

    method scan_literal($item, $pos, $text) {
        DEBUG "Scanning literal at position $pos";
        my $literal = $item->next_symbol;
        DEBUG "Literal: $literal";
        my $lit_length = length($literal);

        DEBUG "comparing $pos + $lit_length to " . length($text);
        return if $pos + $lit_length > length($text);
        DEBUG "Literal length: $lit_length";

        my $text_part = substr($text, $pos, $lit_length);
        DEBUG "Text part: $text_part";
        if ($text_part eq $literal) {
            DEBUG "Matched literal: $literal";
            my $new_item = $item->advance($literal);
            $new_item->set_current_pos($pos + $lit_length);

            push @{$chart[$pos + $lit_length]}, $new_item;
        }
    }

    method predict($item, $pos, $agenda) {
        my $next_sym = $item->next_symbol;
        DEBUG "Predicting for symbol: $next_sym at position $pos";

        for my $rule (@grammar_rules) {
            if ($rule->lhs eq $next_sym) {
                DEBUG "Found rule to predict: " . $rule->to_string;
                my $predicted_item = EarleyItem->new(
                    rule => $rule,
                    start_pos => $pos,
                    current_pos => $pos
                );

                # Check if this exact item already exists using content-based comparison
                my $already_exists = 0;
                for my $existing_item (@{$chart[$pos]}) {
                    if ($existing_item->rule == $rule && 
                        $existing_item->start_pos == $pos && 
                        $existing_item->dot_pos == 0) {
                        DEBUG "Rule already predicted, skipping";
                        $already_exists = 1;
                        last;
                    }
                }
                
                if (!$already_exists) {
                    DEBUG "Adding predicted item: " . $predicted_item->to_string;
                    push @$agenda, $predicted_item;
                    push @{$chart[$pos]}, $predicted_item;
                }
            }
        }
    }

    method is_character_class($symbol) {
        return $symbol =~ /^(Letter|LetterDigit|Char|Whitespace|CommentLineChar)$/;
    }


    method matches_character_class($char, $class) {
        for ($class) {
            if ($_ eq 'Letter') { return $char =~ /[a-zA-Z]/ }
            if ($_ eq 'LetterDigit') { return $char =~ /[a-zA-Z0-9]/ }
            if ($_ eq 'Char') { return $char =~ /[^"']/ }  # Any char except quotes
            if ($_ eq 'Whitespace') { return $char =~ /\s/ }
            if ($_ eq 'CommentLineChar') { return $char =~ /[^\n]/ }  # Any char except newline
            return 0;
        }
    }
}

# Command-line argument processing
use Getopt::Long;

my $help;

GetOptions(
    'h|help' => \$help,
) or die "Error in command line arguments\n";

if ($help) {
    print <<'USAGE';
Usage: chalk [filename]
  -h, --help    Show this help message

If no filename is given, code is read from STDIN.
USAGE
    exit 0;
}

my $perl_code;

if (@ARGV) {
    # Read from file
    my $filename = $ARGV[0];
    open my $fh, '<', $filename or die "Cannot open file '$filename': $!\n";
    $perl_code = do { local $/; <$fh> };
    close $fh;
} else {
    # Read from STDIN
    $perl_code = do { local $/; <STDIN> };
}

die "No code to execute\n" unless defined $perl_code && length $perl_code;

# Parse and execute the code
my $parser = ScanlessEarleyParser->new();
my $ir_graph = $parser->parse($perl_code);

# Run optimizations and cleanup (peephole optimizations run in execute_threaded)
$ir_graph->cleanup_orphaned_nodes();
# $ir_graph->dump_graph();  # Temporarily disabled to test theories

# Execute the code
$ir_graph->execute_threaded();
