/* ABOUTME: C implementation of Chalk::Bootstrap::Semiring::Boolean (generated by Target::C). */
/* ABOUTME: Auto-generated from Perl source — do not edit. */
#include "chalk.h"
#include "boolean.h"

/* File-scope statics (class-scope lexicals) */
static SV *_csv_boolean_ONE_CTX = NULL;
static SV *_csv_boolean_ZERO_CTX = NULL;

/* One-time static initializer — called from BOOT */
void boolean_init_statics(pTHX) {
    static int _initialized = 0;
    if (_initialized) return;
    _initialized = 1;
}

/* Exported functions */
SV * boolean_zero(pTHX_ SV *self) {
    SV *retval = NULL;
    ({ if (!_csv_boolean_ZERO_CTX || !SvOK(_csv_boolean_ZERO_CTX)) { _csv_boolean_ZERO_CTX = SvREFCNT_inc_simple(({ dSP; ENTER; SAVETMPS; PUSHMARK(SP); XPUSHs(sv_2mortal(newSVpvs("Chalk::Bootstrap::Context"))); XPUSHs(sv_2mortal(newSVpvs("focus"))); XPUSHs(&PL_sv_undef); XPUSHs(sv_2mortal(newSVpvs("children"))); XPUSHs(sv_2mortal(newRV_noinc((SV*)newAV()))); XPUSHs(sv_2mortal(newSVpvs("is_zero"))); XPUSHs(&PL_sv_yes); PUTBACK; call_method("new", G_SCALAR); SPAGAIN; SV *_mcr = SvREFCNT_inc(POPs); PUTBACK; FREETMPS; LEAVE; _mcr; })); } _csv_boolean_ZERO_CTX; });
    retval = SvREFCNT_inc(_csv_boolean_ZERO_CTX);
    return retval;
}

SV * boolean_one(pTHX_ SV *self) {
    SV *retval = NULL;
    ({ if (!_csv_boolean_ONE_CTX || !SvOK(_csv_boolean_ONE_CTX)) { _csv_boolean_ONE_CTX = SvREFCNT_inc_simple(({ dSP; ENTER; SAVETMPS; PUSHMARK(SP); XPUSHs(sv_2mortal(newSVpvs("Chalk::Bootstrap::Context"))); XPUSHs(sv_2mortal(newSVpvs("focus"))); XPUSHs(&PL_sv_yes); XPUSHs(sv_2mortal(newSVpvs("children"))); XPUSHs(sv_2mortal(newRV_noinc((SV*)newAV()))); XPUSHs(sv_2mortal(newSVpvs("is_zero"))); XPUSHs(&PL_sv_no); PUTBACK; call_method("new", G_SCALAR); SPAGAIN; SV *_mcr = SvREFCNT_inc(POPs); PUTBACK; FREETMPS; LEAVE; _mcr; })); } _csv_boolean_ONE_CTX; });
    retval = SvREFCNT_inc(_csv_boolean_ONE_CTX);
    return retval;
}

SV * boolean_is_zero(pTHX_ SV *self, SV *value) {
    SV *retval = NULL;
    if (SvTRUE((SvTRUE((SvOK(value) ? &PL_sv_yes : &PL_sv_no)) ? &PL_sv_no : &PL_sv_yes))) {
        retval = &PL_sv_no; goto xsreturn;
    }
    if (SvTRUE((SvTRUE((SvROK(value) ? sv_2mortal(newSVpv(sv_reftype(SvRV(value), TRUE), 0)) : sv_2mortal(newSVpvs("")))) ? &PL_sv_no : &PL_sv_yes))) {
        retval = &PL_sv_no; goto xsreturn;
    }
    if (SvTRUE((SvTRUE((SvTRUE((SvROK(value) && sv_isobject(value) ? sv_2mortal(newSVpv(HvNAME(SvSTASH(SvRV(value))), 0)) : &PL_sv_undef)) ? ({ dSP; ENTER; SAVETMPS; PUSHMARK(SP); XPUSHs(value); XPUSHs(sv_2mortal(newSVpvs("Chalk::Bootstrap::Context"))); PUTBACK; call_method("isa", G_SCALAR); SPAGAIN; SV *_mcr = SvREFCNT_inc(POPs); PUTBACK; FREETMPS; LEAVE; _mcr; }) : &PL_sv_no)) ? &PL_sv_no : &PL_sv_yes))) {
        retval = &PL_sv_no; goto xsreturn;
    }
    retval = (SvTRUE(({ dSP; ENTER; SAVETMPS; PUSHMARK(SP); XPUSHs(value); PUTBACK; call_method("is_zero", G_SCALAR); SPAGAIN; SV *_mcr = SvREFCNT_inc(POPs); PUTBACK; FREETMPS; LEAVE; _mcr; })) ? &PL_sv_yes : &PL_sv_no);
    xsreturn:
    return retval;
}

SV * boolean_multiply(pTHX_ SV *self, SV *left, SV *right) {
    SV *retval = NULL;
    SV *self_sv = NULL;
    if (SvTRUE(({ boolean_is_zero(aTHX_ self, left); }))) {
        retval = SvREFCNT_inc(({ boolean_zero(aTHX_ self); })); goto xsreturn;
    }
    retval = (SvTRUE(({ boolean_is_zero(aTHX_ self, right); })) ? ({ boolean_zero(aTHX_ self); }) : ({ dSP; ENTER; SAVETMPS; PUSHMARK(SP); XPUSHs(sv_2mortal(newSVpvs("Chalk::Bootstrap::Context"))); XPUSHs(sv_2mortal(newSVpvs("focus"))); XPUSHs(&PL_sv_yes); XPUSHs(sv_2mortal(newSVpvs("children"))); XPUSHs(({ AV *_arr8407 = newAV(); av_push(_arr8407, SvREFCNT_inc(left)); av_push(_arr8407, SvREFCNT_inc(right)); sv_2mortal(newRV_noinc((SV*)_arr8407)); })); XPUSHs(sv_2mortal(newSVpvs("is_zero"))); XPUSHs(&PL_sv_no); PUTBACK; call_method("new", G_SCALAR); SPAGAIN; SV *_mcr = SvREFCNT_inc(POPs); PUTBACK; FREETMPS; LEAVE; _mcr; }));
    xsreturn:
    return retval;
}

SV * boolean_add(pTHX_ SV *self, SV *left, SV *right) {
    SV *retval = NULL;
    SV *lz_sv = NULL;
    SV *rz_sv = NULL;
    SV *self_sv = NULL;
    lz_sv = ({ boolean_is_zero(aTHX_ self, left); });
    rz_sv = ({ boolean_is_zero(aTHX_ self, right); });
    if (SvTRUE((SvTRUE(lz_sv) ? rz_sv : &PL_sv_no))) {
        retval = SvREFCNT_inc(({ boolean_zero(aTHX_ self); })); goto xsreturn;
    }
    if (SvTRUE(lz_sv)) {
        retval = SvREFCNT_inc(right); goto xsreturn;
    }
    retval = SvREFCNT_inc(left);
    xsreturn:
    return retval;
}

SV * boolean_slot_name(pTHX_ SV *self) {
    return &PL_sv_undef;
}
