# ABOUTME: End-to-end test for chalk.so + thin XS wrapper build pipeline.
# ABOUTME: Compiles hand-crafted boolean.c into chalk.so, validates loading and calling.
use 5.42.0;
use utf8;
use Test::More;
use File::Temp qw(tempdir);
use File::Path qw(make_path);
use Config;

my $have_compiler;
eval {
    require ExtUtils::CBuilder;
    $have_compiler = ExtUtils::CBuilder->new(quiet => 1)->have_compiler;
};
plan skip_all => 'No C compiler available' unless $have_compiler;

my $tmpdir = tempdir(CLEANUP => 1);
my $perl = $^X;
my $archlib = $Config{archlib};
my $ccflags = $Config{ccflags};
my $cc = $Config{cc};
my $so_ext = $Config{dlext};

# Locate hand-crafted C fixtures relative to this test file
my $c_src = do {
    use File::Basename qw(dirname);
    use Cwd qw(abs_path);
    my $dir = abs_path(dirname(__FILE__));
    abs_path("$dir/../fixtures/c_src");
};

# Emit chalk.h into $tmpdir via Target::C (matches generated-code pipeline)
use lib 'lib';
require Chalk::Bootstrap::BNF::Target::C;
{
    my $target_c = Chalk::Bootstrap::BNF::Target::C->new();
    open my $fh, '>', "$tmpdir/chalk.h" or die "write chalk.h: $!";
    print $fh $target_c->generate_runtime_header();
    close $fh;
}

# Test 1: boolean.c compiles
my $cmd = "$cc -c -fPIC $ccflags -I$archlib/CORE -I$c_src -I$tmpdir $c_src/boolean.c -o $tmpdir/boolean.o 2>&1";
my $out = `$cmd`;
is($? >> 8, 0, 'boolean.c compiles to boolean.o') or diag("Compile failed: $out\nCommand: $cmd");

# Test 2: links into chalk.so
$cmd = "$cc -shared -fPIC $tmpdir/boolean.o -o $tmpdir/chalk.$so_ext 2>&1";
$out = `$cmd`;
is($? >> 8, 0, 'boolean.o links into chalk.so') or diag("Link failed: $out\nCommand: $cmd");

# Test 3: chalk.so exists
ok(-f "$tmpdir/chalk.$so_ext", 'chalk.so exists');

# Test 4: chalk.so loads and has our symbol
my $load_script = "$tmpdir/load_test.pl";
open my $lfh, '>', $load_script or die "Cannot write $load_script: $!";
print $lfh <<"END_SCRIPT";
use 5.42.0;
require DynaLoader;
my \$libref = DynaLoader::dl_load_file("$tmpdir/chalk.$so_ext", 0x01);
if (\$libref) {
    print "LOADED\\n";
    my \$sym = DynaLoader::dl_find_symbol(\$libref, "boolean_is_zero");
    print defined \$sym ? "SYMBOL_FOUND\\n" : "SYMBOL_MISSING\\n";
} else {
    print "LOAD_FAILED: " . DynaLoader::dl_error() . "\\n";
}
END_SCRIPT
close $lfh;
$out = `$perl $load_script 2>&1`;
like($out, qr/LOADED/, 'chalk.so loads via DynaLoader');
like($out, qr/SYMBOL_FOUND/, 'boolean_is_zero symbol found in chalk.so');

# ---- XS wrapper tests ----
my $privlib = $Config{privlibexp};
my $xsubpp  = "$privlib/ExtUtils/xsubpp";
my $typemap = "$privlib/ExtUtils/typemap";

# Test 6: xsubpp processes Boolean.xs
$cmd = "$perl $xsubpp -typemap $typemap $c_src/Boolean.xs 2>&1";
$out = `$cmd`;
is($? >> 8, 0, 'xsubpp processes Boolean.xs without error')
    or diag("xsubpp failed:\n$out");
my $boolean_c = "$tmpdir/Boolean.c";
open my $bfh, '>', $boolean_c or die "Cannot write $boolean_c: $!";
print $bfh $out;
close $bfh;
ok(-f $boolean_c && -s $boolean_c, 'Boolean.c generated by xsubpp has content');

# Test 7: compile xsubpp output into Boolean.o
$cmd = "$cc -c -fPIC $ccflags -I$archlib/CORE -I$c_src -I$tmpdir $boolean_c -o $tmpdir/Boolean.o 2>&1";
$out = `$cmd`;
is($? >> 8, 0, 'Boolean.c (xsubpp output) compiles to Boolean.o')
    or diag("Compile failed: $out\nCommand: $cmd");

# Test 8: link into Boolean.so, resolving boolean_* symbols from chalk.so
$cmd = "$cc -shared -fPIC $tmpdir/Boolean.o $tmpdir/chalk.$so_ext -o $tmpdir/Boolean.$so_ext 2>&1";
$out = `$cmd`;
is($? >> 8, 0, 'Boolean.o links into Boolean.so')
    or diag("Link failed: $out\nCommand: $cmd");

ok(-f "$tmpdir/Boolean.$so_ext", 'Boolean.so exists');

# Build a minimal blib layout for require to find the .so
use File::Path qw(make_path);
my $blib_arch = "$tmpdir/blib/arch/auto/Chalk/Bootstrap/Semiring/Boolean";
my $blib_lib  = "$tmpdir/blib/lib/Chalk/Bootstrap/Semiring";
make_path($blib_arch);
make_path($blib_lib);

# Copy the compiled .so into blib
use File::Copy qw(copy);
copy("$tmpdir/Boolean.$so_ext", "$blib_arch/Boolean.$so_ext")
    or die "copy failed: $!";

# Write a stub .pm loader that uses dl_install_xsub (same pattern as
# generated XS stubs) so the BOOT block runs without DynaLoader::bootstrap_inherit
# adding 'DynaLoader' to @ISA (which would prevent class_setup_stash from running).
my $stub_pm = "$blib_lib/Boolean.pm";
open my $sfh, '>', $stub_pm or die "Cannot write $stub_pm: $!";
print $sfh <<"END_PM";
use 5.42.0;
use utf8;
package Chalk::Bootstrap::Semiring::Boolean;
use strict;
use warnings;
require DynaLoader;

my \$so;
for my \$dir (\@INC) {
    next if ref \$dir;
    my \$path = "\$dir/auto/Chalk/Bootstrap/Semiring/Boolean/Boolean.$so_ext";
    if (-f \$path) { \$so = \$path; last; }
}
die "Cannot locate Boolean.$so_ext in \@INC" unless defined \$so;

my \$libref = DynaLoader::dl_load_file(\$so, 0)
    or die "dl_load_file: " . DynaLoader::dl_error();
my \$boot = DynaLoader::dl_find_symbol(\$libref, "boot_Chalk__Bootstrap__Semiring__Boolean")
    or die "dl_find_symbol: " . DynaLoader::dl_error();
DynaLoader::dl_install_xsub("Chalk::Bootstrap::Semiring::Boolean::_bootstrap", \$boot, \$so);
Chalk::Bootstrap::Semiring::Boolean->_bootstrap();

1;
END_PM
close $sfh;

# Test 9-11: load chalk.so + Boolean.so and call all methods in subprocess
my $method_script = "$tmpdir/method_test.pl";
open my $mfh, '>', $method_script or die "Cannot write $method_script: $!";
print $mfh <<"END_SCRIPT";
use 5.42.0;
use utf8;
use lib "$tmpdir/blib/arch";
use lib "$tmpdir/blib/lib";
require DynaLoader;

# chalk.so must be loaded with RTLD_GLOBAL (0x101 = RTLD_GLOBAL|RTLD_NOW)
# so that boolean_* symbols are visible when Boolean.so loads.
my \$chalk_ref = DynaLoader::dl_load_file("$tmpdir/chalk.$so_ext", 0x101)
    or die "chalk.so load failed: " . DynaLoader::dl_error();
print "CHALK_LOADED\\n";

require Chalk::Bootstrap::Semiring::Boolean;
print "BOOLEAN_MODULE_LOADED\\n";

my \$b = Chalk::Bootstrap::Semiring::Boolean->new();
print "INSTANCE_CREATED\\n";

my \$zero = \$b->zero();
my \$one  = \$b->one();

print \$b->is_zero(\$zero) ? "IS_ZERO_CORRECT\\n"  : "IS_ZERO_WRONG\\n";
print !\$b->is_zero(\$one) ? "IS_ONE_CORRECT\\n"   : "IS_ONE_WRONG\\n";

my \$r1 = \$b->multiply(\$zero, \$one);
print \$b->is_zero(\$r1) ? "MULTIPLY_CORRECT\\n"   : "MULTIPLY_WRONG\\n";

my \$r2 = \$b->add(\$zero, \$one);
print !\$b->is_zero(\$r2) ? "ADD_CORRECT\\n"       : "ADD_WRONG\\n";

print \$b->should_scan('TestRule', 0, 0, "", {}) ? "SHOULD_SCAN_OK\\n" : "SHOULD_SCAN_FAIL\\n";
print \$b->supports_leo() ? "SUPPORTS_LEO_OK\\n" : "SUPPORTS_LEO_FAIL\\n";
print "ALL_METHODS_OK\\n";
END_SCRIPT
close $mfh;

$out = `$perl $method_script 2>&1`;
like($out, qr/CHALK_LOADED/,         'chalk.so loads with RTLD_GLOBAL');
like($out, qr/BOOLEAN_MODULE_LOADED/, 'Boolean XS module loads via require');
like($out, qr/ALL_METHODS_OK/,        'all Boolean methods work via XS')
    or diag("Method test output:\n$out");

done_testing;
