# ABOUTME: Tests C-backed data model classes (Symbol, Rule, CoreItemIndex, LR0DFA).
# ABOUTME: Verifies codegen shape and behavioral correctness via subprocess loading.
use 5.42.0;
use utf8;
use Test::More;
use File::Temp qw(tempdir tempfile);
use File::Basename qw(dirname);
use File::Copy qw(copy);
use File::Path qw(make_path);
use Cwd qw(abs_path);
use Config;

use lib 'lib';
use lib 't/bootstrap/lib';

use TestXSHelpers qw(setup_xs_grammar parse_file_ir);
use Chalk::Bootstrap::Perl::Target::C;

my $so_ext    = $Config{dlext};
my $repo_root = abs_path(dirname(__FILE__) . '/../..');
my $build_dir = "$repo_root/.build/chalk-so-gen";
my $chalk_so  = "$build_dir/chalk.$so_ext";
my $perl      = $^X;

# =========================================================================
# Part 1: Codegen shape tests — verify Target::C handles these classes
# =========================================================================

my $gen = eval { setup_xs_grammar('Chalk::Grammar::Perl::CDataModel') };
ok(defined $gen, 'grammar pipeline built')
    or BAIL_OUT("Cannot continue without grammar: $@");

# --- Symbol.pm ---
{
    my ($ir, $sa, $ctx) = eval {
        parse_file_ir($gen, 'lib/Chalk/Grammar/Symbol.pm')
    };
    ok(defined $ir, 'Symbol.pm parsed to IR')
        or BAIL_OUT("Cannot parse Symbol.pm: $@");

    my $target = Chalk::Bootstrap::Perl::Target::C->new(
        module_name => 'Chalk::Grammar::Symbol',
    );
    my $result = eval { $target->_generate_c_files($ir, $sa, $ctx) };
    is($@, '', 'Symbol _generate_c_files does not die');
    ok(defined $result, 'Symbol result defined');

    my $c_text = $result->{files}{'symbol.c'};
    ok(defined $c_text, 'symbol.c generated');

    # Explicit methods compile to native C.
    # Note: :reader accessors (type, value, quantifier) are auto-generated by
    # Perl's class API in the BOOT block, not compiled as C functions.
    like($c_text, qr/symbol_is_terminal\(pTHX_/, 'is_terminal() compiled to C');
    like($c_text, qr/symbol_is_reference\(pTHX_/, 'is_reference() compiled to C');
    like($c_text, qr/symbol_is_quantified\(pTHX_/, 'is_quantified() compiled to C');
    like($c_text, qr/symbol_to_string\(pTHX_/, 'to_string() compiled to C');

    # Self-calls: is_terminal() is called in to_string() on $self
    like($c_text, qr/symbol_is_terminal\(aTHX_ self\)/,
        'to_string self-call to is_terminal uses direct C');

    my @skipped = ($result->{skipped_methods} // [])->@*;
    note("Symbol skipped methods: @skipped") if @skipped;
}

# --- Rule.pm ---
{
    my ($ir, $sa, $ctx) = eval {
        parse_file_ir($gen, 'lib/Chalk/Grammar/Rule.pm')
    };
    ok(defined $ir, 'Rule.pm parsed to IR')
        or BAIL_OUT("Cannot parse Rule.pm: $@");

    my $target = Chalk::Bootstrap::Perl::Target::C->new(
        module_name => 'Chalk::Grammar::Rule',
    );
    my $result = eval { $target->_generate_c_files($ir, $sa, $ctx) };
    is($@, '', 'Rule _generate_c_files does not die');

    my $c_text = $result->{files}{'rule.c'};
    ok(defined $c_text, 'rule.c generated');

    # name() and expressions() are :reader — auto-generated by class API, not C functions.
    # Explicit methods should compile:
    like($c_text, qr/rule_alternative_count\(pTHX_/, 'alternative_count() compiled to C');

    my @skipped = ($result->{skipped_methods} // [])->@*;
    note("Rule skipped methods: @skipped") if @skipped;
}

# --- CoreItemIndex.pm ---
{
    my ($ir, $sa, $ctx) = eval {
        parse_file_ir($gen, 'lib/Chalk/Bootstrap/CoreItemIndex.pm')
    };
    ok(defined $ir, 'CoreItemIndex.pm parsed to IR')
        or BAIL_OUT("Cannot parse CoreItemIndex.pm: $@");

    my $target = Chalk::Bootstrap::Perl::Target::C->new(
        module_name => 'Chalk::Bootstrap::CoreItemIndex',
    );
    my $result = eval { $target->_generate_c_files($ir, $sa, $ctx) };
    is($@, '', 'CoreItemIndex _generate_c_files does not die');

    my $c_text = $result->{files}{'coreitemindex.c'};
    ok(defined $c_text, 'coreitemindex.c generated');

    # Hot-path methods must compile (count is :reader, auto-generated)
    like($c_text, qr/coreitemindex_id_for\(pTHX_/, 'id_for() compiled to C');
    like($c_text, qr/coreitemindex_item_for\(pTHX_/, 'item_for() compiled to C');
    like($c_text, qr/coreitemindex_advance\(pTHX_/, 'advance() compiled to C');
    like($c_text, qr/coreitemindex_register\(pTHX_/, 'register() compiled to C');

    # advance() calls $self->id_for() — should be direct self-call
    like($c_text, qr/coreitemindex_id_for\(aTHX_ self/,
        'advance self-call to id_for uses direct C');

    my @skipped = ($result->{skipped_methods} // [])->@*;
    note("CoreItemIndex skipped methods: @skipped") if @skipped;
}

# --- LR0DFA.pm ---
{
    my ($ir, $sa, $ctx) = eval {
        parse_file_ir($gen, 'lib/Chalk/Bootstrap/LR0DFA.pm')
    };
    ok(defined $ir, 'LR0DFA.pm parsed to IR')
        or BAIL_OUT("Cannot parse LR0DFA.pm: $@");

    my $target = Chalk::Bootstrap::Perl::Target::C->new(
        module_name => 'Chalk::Bootstrap::LR0DFA',
    );
    my $result = eval { $target->_generate_c_files($ir, $sa, $ctx) };
    is($@, '', 'LR0DFA _generate_c_files does not die');

    my $c_text = $result->{files}{'lr0dfa.c'};
    ok(defined $c_text, 'lr0dfa.c generated');

    # Hot-path method must compile
    like($c_text, qr/lr0dfa_prediction_items_for\(pTHX_/, 'prediction_items_for() compiled to C');
    like($c_text, qr/lr0dfa_is_nullable\(pTHX_/, 'is_nullable() compiled to C');

    # Construction-time methods may be skipped — that's acceptable
    my @skipped = ($result->{skipped_methods} // [])->@*;
    note("LR0DFA skipped methods: @skipped") if @skipped;

    # Verify hot-path methods are NOT in skipped list
    ok(!grep({ $_ eq 'prediction_items_for' } @skipped),
        'prediction_items_for is NOT skipped');
    ok(!grep({ $_ eq 'is_nullable' } @skipped),
        'is_nullable is NOT skipped');
}

# =========================================================================
# Part 2: Behavioral test — load C-backed data model classes in subprocess
# =========================================================================

# Skip if chalk.so hasn't been rebuilt with the 4 new classes
my @data_model_classes = (
    { pkg => 'Chalk::Grammar::Symbol',          slug => 'symbol' },
    { pkg => 'Chalk::Grammar::Rule',            slug => 'rule' },
    { pkg => 'Chalk::Bootstrap::CoreItemIndex', slug => 'coreitemindex' },
    { pkg => 'Chalk::Bootstrap::LR0DFA',        slug => 'lr0dfa' },
);

sub class_so_path($pkg) {
    my $pkg_path = $pkg =~ s{::}{/}gr;
    my $base     = ($pkg =~ /(\w+)$/)[0];
    return "$build_dir/auto/$pkg_path/$base.$so_ext";
}

my $all_built = true;
for my $c (@data_model_classes) {
    unless (-f class_so_path($c->{pkg})) {
        $all_built = false;
        last;
    }
}

SKIP: {
    skip "Data model classes not yet built in chalk.so", 10 unless $all_built && -f $chalk_so;

    # Build blib layout with stubs for the 4 data model classes
    my $tmpdir   = tempdir(CLEANUP => 1);
    my $blib_lib = "$tmpdir/blib/lib";

    for my $c (@data_model_classes) {
        my $pkg      = $c->{pkg};
        my $so_path  = class_so_path($pkg);
        my $pkg_path = $pkg =~ s{::}{/}gr;
        my $base     = ($pkg =~ /(\w+)$/)[0];

        my $arch_dir = "$tmpdir/blib/arch/auto/$pkg_path";
        make_path($arch_dir);
        copy($so_path, "$arch_dir/$base.$so_ext")
            or die "copy $base.$so_ext failed: $!";

        my $pm_dir = "$blib_lib/" . ($pkg =~ s{::[^:]+$}{}r =~ s{::}{/}gr);
        make_path($pm_dir);
        my $pm_file = "$blib_lib/${pkg_path}.pm";
        my $boot_sym = "boot_" . ($pkg =~ s/::/__/gr);

        open my $fh, '>', $pm_file or die "Cannot write $pm_file: $!";
        print $fh <<"END_PM";
package $pkg;
use strict;
use warnings;
require DynaLoader;

my \$so;
for my \$dir (\@INC) {
    next if ref \$dir;
    my \$path = "\$dir/auto/$pkg_path/$base.$so_ext";
    if (-f \$path) { \$so = \$path; last; }
}
die "Cannot locate $base.$so_ext in \\\@INC" unless defined \$so;

my \$libref = DynaLoader::dl_load_file(\$so, 0)
    or die "dl_load_file $base: " . DynaLoader::dl_error();
my \$boot = DynaLoader::dl_find_symbol(\$libref, "$boot_sym")
    or die "dl_find_symbol $boot_sym: " . DynaLoader::dl_error();
DynaLoader::dl_install_xsub("${pkg}::_bootstrap", \$boot, \$so);
${pkg}->_bootstrap();

1;
END_PM
        close $fh;
    }

    my $lib_arch    = "use lib '$tmpdir/blib/arch';";
    my $lib_pm      = "use lib '$tmpdir/blib/lib';";
    my $lib_project = "use lib '$repo_root/lib';";
    my $chalk_load  = "require DynaLoader; "
        . "DynaLoader::dl_load_file('$chalk_so', 0x01) "
        . "or die 'chalk.so: ' . DynaLoader::dl_error();";

    sub run_subprocess($code) {
        my (undef, $script_file) = tempfile(SUFFIX => '.pl', UNLINK => 1, DIR => $tmpdir);
        open my $fh, '>:utf8', $script_file or die "Cannot write $script_file: $!";
        print $fh $code;
        close $fh;
        my $out = `$perl $script_file 2>&1`;
        return ($out, $? >> 8);
    }

    my ($out, $exit) = run_subprocess(<<"END_SCRIPT");
use 5.42.0;
use utf8;
$lib_arch
$lib_pm
$lib_project
$chalk_load

require Chalk::Grammar::Symbol;
require Chalk::Grammar::Rule;
require Chalk::Bootstrap::CoreItemIndex;
require Chalk::Bootstrap::LR0DFA;

# --- Test Symbol ---
my \$sym_t = Chalk::Grammar::Symbol->new(type => 'terminal', value => '/[a-z]+/');
print "SYM_TYPE:" . \$sym_t->type() . "\\n";
print "SYM_VALUE:" . \$sym_t->value() . "\\n";
print "SYM_IS_TERM:" . (\$sym_t->is_terminal() ? '1' : '0') . "\\n";
print "SYM_IS_REF:" . (\$sym_t->is_reference() ? '1' : '0') . "\\n";

my \$sym_r = Chalk::Grammar::Symbol->new(type => 'reference', value => 'Expr', quantifier => '*');
print "SYM_QUANT:" . \$sym_r->quantifier() . "\\n";
print "SYM_IS_Q:" . (\$sym_r->is_quantified() ? '1' : '0') . "\\n";

# --- Test Rule ---
my \$rule = Chalk::Grammar::Rule->new(
    name => 'TestRule',
    expressions => [
        [Chalk::Grammar::Symbol->new(type => 'reference', value => 'A')],
        [Chalk::Grammar::Symbol->new(type => 'terminal', value => '/x/')],
    ],
);
print "RULE_NAME:" . \$rule->name() . "\\n";
print "RULE_ALT_COUNT:" . \$rule->alternative_count() . "\\n";
print "RULE_EXPRS:" . ref(\$rule->expressions()) . "\\n";

# --- Test CoreItemIndex ---
my \$idx = Chalk::Bootstrap::CoreItemIndex->new();
my \$id0 = \$idx->register('A', 0, 0);
my \$id1 = \$idx->register('A', 0, 1);
my \$id2 = \$idx->register('A', 0, 0);  # duplicate
print "IDX_ID0:" . \$id0 . "\\n";
print "IDX_ID1:" . \$id1 . "\\n";
print "IDX_DUP:" . \$id2 . "\\n";  # should equal id0
print "IDX_LOOKUP:" . (\$idx->id_for('A', 0, 1) // 'undef') . "\\n";
my \$info = \$idx->item_for(\$id0);
print "IDX_INFO:" . \$info->{rule_name} . ":" . \$info->{alt_idx} . ":" . \$info->{dot} . "\\n";
my \$adv = \$idx->advance(\$id0);
print "IDX_ADVANCE:" . (\$adv // 'undef') . "\\n";

print "ALL_OK\\n";
END_SCRIPT

    is($exit, 0, 'data model subprocess exits cleanly')
        or diag("Output:\n$out");

    like($out, qr/SYM_TYPE:terminal/, 'Symbol type() works');
    like($out, qr/SYM_VALUE:\/\[a-z\]\+\//, 'Symbol value() works');
    like($out, qr/SYM_IS_TERM:1/, 'Symbol is_terminal() works');
    like($out, qr/SYM_IS_REF:0/, 'Symbol is_reference() works');
    like($out, qr/SYM_QUANT:\*/, 'Symbol quantifier() works');
    like($out, qr/SYM_IS_Q:1/, 'Symbol is_quantified() works');
    like($out, qr/RULE_NAME:TestRule/, 'Rule name() works');
    like($out, qr/RULE_ALT_COUNT:2/, 'Rule alternative_count() works');
    like($out, qr/IDX_DUP:0/, 'CoreItemIndex deduplicates (same id)');
    like($out, qr/IDX_ADVANCE:1/, 'CoreItemIndex advance() works');
    like($out, qr/ALL_OK/, 'all data model tests passed');
}

done_testing;
