# ABOUTME: Unit tests for XS AST node emit() methods.
# ABOUTME: Verifies each AST node produces correct XS text fragments.
use 5.42.0;
use utf8;
use Test::More;

use lib 'lib';

# === Node base class ===

use_ok('Chalk::Bootstrap::Target::XS::AST::Node');

{
    my $node = Chalk::Bootstrap::Target::XS::AST::Node->new();
    isa_ok($node, 'Chalk::Bootstrap::Target::XS::AST::Node');

    eval { $node->emit() };
    like($@, qr/Subclass must implement emit/, 'base Node emit() dies');
}

# === Preamble ===

use_ok('Chalk::Bootstrap::Target::XS::AST::Preamble');

{
    my $preamble = Chalk::Bootstrap::Target::XS::AST::Preamble->new();
    isa_ok($preamble, 'Chalk::Bootstrap::Target::XS::AST::Node');
    isa_ok($preamble, 'Chalk::Bootstrap::Target::XS::AST::Preamble');

    my $output = $preamble->emit();
    like($output, qr/#define PERL_NO_GET_CONTEXT/, 'preamble contains PERL_NO_GET_CONTEXT');
    like($output, qr/#include "EXTERN\.h"/, 'preamble contains EXTERN.h');
    like($output, qr/#include "perl\.h"/, 'preamble contains perl.h');
    like($output, qr/#include "XSUB\.h"/, 'preamble contains XSUB.h');
    like($output, qr/Generated by Chalk::Bootstrap/, 'preamble contains generator comment');
    like($output, qr/SVt_PVOBJ/, 'preamble contains direct construction note');
}

# === Module ===

use_ok('Chalk::Bootstrap::Target::XS::AST::Module');

{
    my $module = Chalk::Bootstrap::Target::XS::AST::Module->new(
        module  => 'Chalk::Grammar::BNF::Rules',
        package => 'Chalk::Grammar::BNF::Rules',
    );
    isa_ok($module, 'Chalk::Bootstrap::Target::XS::AST::Node');
    isa_ok($module, 'Chalk::Bootstrap::Target::XS::AST::Module');

    my $output = $module->emit();
    like($output, qr/MODULE = Chalk::Grammar::BNF::Rules/, 'module contains MODULE =');
    like($output, qr/PACKAGE = Chalk::Grammar::BNF::Rules/, 'module contains PACKAGE =');

    is($module->module(), 'Chalk::Grammar::BNF::Rules', 'module reader works');
    is($module->package(), 'Chalk::Grammar::BNF::Rules', 'package reader works');
}

# Module with different module and package names
{
    my $module = Chalk::Bootstrap::Target::XS::AST::Module->new(
        module  => 'Foo::Bar',
        package => 'Foo::Baz',
    );
    my $output = $module->emit();
    like($output, qr/MODULE = Foo::Bar/, 'module name is Foo::Bar');
    like($output, qr/PACKAGE = Foo::Baz/, 'package name is Foo::Baz');
}

# === VarDecl ===

use_ok('Chalk::Bootstrap::Target::XS::AST::VarDecl');

{
    my $var = Chalk::Bootstrap::Target::XS::AST::VarDecl->new(
        type => 'SV *',
        name => 'symbol',
    );
    isa_ok($var, 'Chalk::Bootstrap::Target::XS::AST::Node');
    isa_ok($var, 'Chalk::Bootstrap::Target::XS::AST::VarDecl');

    my $output = $var->emit();
    is($output, "    SV * symbol;\n", 'VarDecl emits correct format');

    is($var->type(), 'SV *', 'type reader works');
    is($var->name(), 'symbol', 'name reader works');
}

# VarDecl with AV * type
{
    my $var = Chalk::Bootstrap::Target::XS::AST::VarDecl->new(
        type => 'AV *',
        name => 'expressions',
    );
    my $output = $var->emit();
    is($output, "    AV * expressions;\n", 'VarDecl with AV * type');
}

# === Statement ===

use_ok('Chalk::Bootstrap::Target::XS::AST::Statement');

{
    my $stmt = Chalk::Bootstrap::Target::XS::AST::Statement->new(
        code => 'expressions = newAV();',
    );
    isa_ok($stmt, 'Chalk::Bootstrap::Target::XS::AST::Node');
    isa_ok($stmt, 'Chalk::Bootstrap::Target::XS::AST::Statement');

    my $output = $stmt->emit();
    is($output, "    expressions = newAV();\n", 'Statement emits with indent');

    is($stmt->code(), 'expressions = newAV();', 'code reader works');
}

# Statement with multi-line call_method block
{
    my $block = "{\n    dSP;\n    ENTER; SAVETMPS;\n    FREETMPS; LEAVE;\n}";
    my $stmt = Chalk::Bootstrap::Target::XS::AST::Statement->new(code => $block);
    my $output = $stmt->emit();
    like($output, qr/dSP/, 'multi-line Statement contains dSP');
    like($output, qr/FREETMPS/, 'multi-line Statement contains FREETMPS');
}

done_testing();
