# ABOUTME: Tests that XS emitter generates static helper functions for complex methods.
# ABOUTME: Verifies same-module self->method() calls use direct C calls instead of call_method.
use 5.42.0;
use utf8;
use Test::More;

use lib 'lib';
use lib 't/bootstrap/lib';

use Chalk::Bootstrap::Perl::Target::XS;
use TestXSHelpers qw(setup_xs_grammar parse_file_ir);

# --- Setup: parse a class with two methods where one calls the other ---

my $gen = eval { setup_xs_grammar('Chalk::Grammar::Perl::XSDirectCall') };
ok(defined $gen, 'grammar pipeline setup') or BAIL_OUT("Cannot continue: $@");

use File::Temp qw(tempfile);
my ($fh, $filename) = tempfile(SUFFIX => '.pm', UNLINK => 1);
print $fh <<'PERL';
use 5.42.0;
use utf8;
no warnings 'experimental::class';

class DirectCallTest {
    field $data :param :reader;

    method helper($x) {
        return $x;
    }

    method caller_method($y) {
        my $result = $self->helper($y);
        return $result;
    }
}
PERL
close $fh;

my ($ir, $sa, $ctx) = eval { parse_file_ir($gen, $filename) };
ok(defined $ir, 'test class parses to IR') or BAIL_OUT("Parse failed: $@");

my $xs = Chalk::Bootstrap::Perl::Target::XS->new(module_name => 'Test::DirectCall');
my $code = eval { $xs->generate_with_cfg($ir, $sa, $ctx) };
ok(defined $code, 'XS code generated') or BAIL_OUT("XS gen failed: $@");

# --- Test 1: Static helper function emitted for complex methods ---
like($code, qr/static\s+SV\s*\*\s*_impl_directcalltest_helper\(pTHX_/,
    'static helper function emitted for helper method');

like($code, qr/static\s+SV\s*\*\s*_impl_directcalltest_caller_method\(pTHX_/,
    'static helper function emitted for caller_method');

# --- Test 2: Helper functions appear BEFORE MODULE line ---
my $module_pos = index($code, 'MODULE =');
my $helper_pos = index($code, '_impl_directcalltest_helper');
ok($helper_pos >= 0 && $module_pos >= 0, 'both helper and MODULE line exist');
ok($helper_pos < $module_pos, 'helper function appears before MODULE line');

# --- Test 3: XSUB wrapper calls _impl_ helper ---
# After the MODULE line, the XSUB wrapper should call the helper
my $after_module = substr($code, $module_pos);
like($after_module, qr/_impl_directcalltest_helper\(aTHX_/,
    'XSUB wrapper for helper calls _impl_directcalltest_helper');
like($after_module, qr/_impl_directcalltest_caller_method\(aTHX_/,
    'XSUB wrapper for caller_method calls _impl_directcalltest_caller_method');

# --- Test 4: Self-method calls use direct helper, not call_method ---
# In the _impl_directcalltest_caller_method body, $self->helper($y) should become
# _impl_directcalltest_helper(aTHX_ self, y) instead of call_method("helper", ...)
like($code, qr/_impl_directcalltest_helper\(aTHX_\s*self/,
    'self->helper() call uses direct _impl_directcalltest_helper(aTHX_ self, ...)');

# The direct call should NOT use call_method for same-module self methods
# Count call_method occurrences — should be zero for "helper" since it's same-module
my @call_method_helper = ($code =~ /call_method\("helper"/g);
is(scalar @call_method_helper, 0,
    'no call_method("helper") — uses direct call instead');

# --- Test 5: Simple methods (Tier A/B) do NOT get helper treatment ---
# The 'data' reader is auto-generated by seal_stash, but if we had a simple
# single-return method, it should stay as a plain XSUB without a helper.
# (helper method returns a parameter — should still be complex enough to get a helper)

# --- Test 6: Non-self method calls still use call_method ---
# Parse a class where a method calls a method on a different object
my ($fh2, $filename2) = tempfile(SUFFIX => '.pm', UNLINK => 1);
print $fh2 <<'PERL';
use 5.42.0;
use utf8;
no warnings 'experimental::class';

class ExternalCallTest {
    field $other :param;

    method do_work() {
        my $result = $other->some_method();
        return $result;
    }
}
PERL
close $fh2;

my ($ir2, $sa2, $ctx2) = eval { parse_file_ir($gen, $filename2) };
ok(defined $ir2, 'external call class parses to IR') or BAIL_OUT("Parse failed: $@");

my $xs2 = Chalk::Bootstrap::Perl::Target::XS->new(module_name => 'Test::ExternalCall');
my $code2 = eval { $xs2->generate_with_cfg($ir2, $sa2, $ctx2) };
ok(defined $code2, 'XS code generated for external call class') or BAIL_OUT("XS gen failed: $@");

# Field-invocant method calls use CV cache (call_sv), not call_method
like($code2, qr/call_sv\(\(SV\s*\*\)_cv_externalcalltest_other_some_method/,
    'field-invocant method calls use CV-cached call_sv');
like($code2, qr/static\s+CV\s*\*\s*_cv_externalcalltest_other_some_method\s*=\s*NULL/,
    'static CV cache variable declared for field method call');

done_testing();
