#!./perl
#
# This is a home for regular expression tests that can't be stored as UTF-8,
# and are big ugly, full of garbage characters, generally generated by
# fuzzers.

use strict;
use warnings;

sub run_tests;

$| = 1;

BEGIN {
    chdir 't' if -d 't';
    require './test.pl';
    set_up_inc('../lib', '.', '../ext/re');
    require Config; import Config;
	require './charset_tools.pl';
    require './loc_tools.pl';
}

skip_all('no re module') unless defined &DynaLoader::boot_DynaLoader;
skip_all('limited memory') if $ENV{'PERL_SKIP_BIG_MEM_TESTS'};

plan tests => 1;  # Update this when adding/deleting tests.

run_tests() unless caller;

#
# Tests start here.
#
sub run_tests {

    {   # [perl #134329]
        my @P;
