; ABOUTME: Hand-written LLVM IR spike for the typed-IR-representation model validation.
; ABOUTME: Represents what SoN->LLVM lowering SHOULD emit for `return 1 + 2` (Phase 3a).
;
; This file is NOT generated by the Chalk compiler. It is hand-authored to stand in
; for a lowering that does not exist yet. Its purpose is to prove that:
;   (a) the LLVM toolchain works for this case, and
;   (b) the model's intended lowering target (add i64 1, 2, print result) is runnable
;       and matches the perl oracle (stdout "3").
;
; SoN graph for `return 1 + 2` under the typed-IR-representation model:
;   Constant(1, repr=Int) : i64  -- no Coerce node needed (Int literal -> i64 directly)
;   Constant(2, repr=Int) : i64  -- same
;   Add(lhs, rhs)         : i64  -- integer add, no libperl needed
;   Return(add_result)           -- make result observable
;
; Observable via printf("3\n") so lli output matches perl's print.

@fmt = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1

declare i32 @printf(i8* nocapture readonly, ...)

define i32 @main() {
entry:
  ; Two Int-representation literals: Constant(1) and Constant(2)
  ; These are i64 in the typed model; use i64 here and truncate to i32 for printf
  %lhs    = add i64 0, 1          ; Constant node: value=1, repr=Int -> i64
  %rhs    = add i64 0, 2          ; Constant node: value=2, repr=Int -> i64

  ; Add node: i64 integer add — no Coerce node needed (both operands already Int)
  %result = add i64 %lhs, %rhs   ; result = 3 as i64

  ; Make result observable: print via printf (printf wants i32, truncate from i64)
  %result_i32 = trunc i64 %result to i32
  %fmt_ptr = getelementptr inbounds [4 x i8], [4 x i8]* @fmt, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt_ptr, i32 %result_i32)

  ret i32 0
}
